export const initialState = {
  posts: {
    data: [
      {
        id: 1,
        title: 'Honda Legend',
        content: 'Sprzedam Legende stan KOLEKCJONERSKI!!!',
        dateOfPublication: '04.09.2020',
        updateDate: '03.09.2020',
        email: 'chris@example.com',
        status: 'published',
        image: '',
        price: 60000,
        userId: 'user_1',
      },
      {
        id: 2,
        title: 'Honda Civic',
        content: 'Sprzedam CIVIC zadbany',
        dateOfPublication: '31.08.2020',
        updateDate: '01.09.2020',
        email: 'john@example.com',
        status: 'closed',
        image: '',
        price: 10000,
        userId: 'user_2',
      },
      {
        id: 3,
        title: 'Audi A4',
        content: 'Sprzedam AUDI Małysza :)',
        dateOfPublication: '20.08.2020',
        updateDate: '03.09.2020',
        email: 'adam@example.com',
        status: 'closed',
        image: '',
        price: 15000,
        userId: 'user_3',
      },
      {
        id: 4,
        title: 'Mercedes S500',
        content: 'Sprzedam idealna limuzynę',
        dateOfPublication: '03.09.2020',
        updateDate: '03.09.2020',
        email: 'benz@example.com',
        status: 'published',
        image: '',
        price: 80000,
        userId: 'user_4',
      },
      {
        id: 5,
        title: 'BMW 330i',
        content: 'Sprzedam 330 stan igła nigdy nie UPALANA!!!',
        dateOfPublication: '03.09.2020',
        updateDate: '',
        email: 'mati@example.com',
        status: 'published',
        image: '',
        price: 20000,
        userId: 'user_5',
      },
      {
        id: 6,
        title: 'Lexus IS 300',
        content: 'Sprzedam IS w doskonałym stanie',
        dateOfPublication: '01.09.2020',
        updateDate: '03.09.2020',
        email: 'anna@example.com',
        status: 'closed',
        image: '',
        price: 30000,
        userId: 'user_6',
      },
      {
        id: 7,
        title: 'Range Rover HSE Sport',
        content: 'Sprzedam pojazd królowej',
        dateOfPublication: '28.08.2020',
        updateDate: '29.08.2020',
        email: 'harry.meghan@example.com',
        status: 'published',
        image: '',
        price: 50000,
        userId: 'user_7',
      },
      {
        id: 8,
        title: 'Ford Mondeo',
        content: 'Sprzedam Forda nic wiecej nie trzeba dodawać',
        dateOfPublication: '01.09.2020',
        updateDate: '02.09.2020',
        email: 'ron@example.com',
        status: 'published',
        image: '',
        price: 1000,
        userId: 'user_8',
      },

    ],
    loading: {
      active: false,
      error: false,
    },
  },
};
